// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/topic.proto
#undef CHECK
#ifndef PROTOBUF_protobuf_2ftopic_2eproto__INCLUDED
#define PROTOBUF_protobuf_2ftopic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace octopus {
class GenericTopic;
class GenericTopicDefaultTypeInternal;
extern GenericTopicDefaultTypeInternal _GenericTopic_default_instance_;
}  // namespace octopus

namespace octopus {

namespace protobuf_protobuf_2ftopic_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_protobuf_2ftopic_2eproto

// ===================================================================

class GenericTopic : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:octopus.GenericTopic) */ {
 public:
  GenericTopic();
  virtual ~GenericTopic();

  GenericTopic(const GenericTopic& from);

  inline GenericTopic& operator=(const GenericTopic& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GenericTopic& default_instance();

  static inline const GenericTopic* internal_default_instance() {
    return reinterpret_cast<const GenericTopic*>(
               &_GenericTopic_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GenericTopic* other);

  // implements Message ----------------------------------------------

  inline GenericTopic* New() const PROTOBUF_FINAL { return New(NULL); }

  GenericTopic* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GenericTopic& from);
  void MergeFrom(const GenericTopic& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GenericTopic* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 1;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:octopus.GenericTopic)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  mutable int _cached_size_;
  friend struct protobuf_protobuf_2ftopic_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GenericTopic

// string msg = 1;
inline void GenericTopic::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GenericTopic::msg() const {
  // @@protoc_insertion_point(field_get:octopus.GenericTopic.msg)
  return msg_.GetNoArena();
}
inline void GenericTopic::set_msg(const ::std::string& value) {

  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:octopus.GenericTopic.msg)
}
#if LANG_CXX11
inline void GenericTopic::set_msg(::std::string&& value) {

  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:octopus.GenericTopic.msg)
}
#endif
inline void GenericTopic::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);

  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:octopus.GenericTopic.msg)
}
inline void GenericTopic::set_msg(const char* value, size_t size) {

  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:octopus.GenericTopic.msg)
}
inline ::std::string* GenericTopic::mutable_msg() {

  // @@protoc_insertion_point(field_mutable:octopus.GenericTopic.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GenericTopic::release_msg() {
  // @@protoc_insertion_point(field_release:octopus.GenericTopic.msg)

  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GenericTopic::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {

  } else {

  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:octopus.GenericTopic.msg)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace octopus

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protobuf_2ftopic_2eproto__INCLUDED
